name: Install dependencies
description: Setup Yarn and Node.js and installs dependencies for the workflow
runs:
  using: composite
  steps:
    # This action assumes the repository has already been checked out
    - name: Setup Yarn
      shell: bash
      run: |
        corepack enable yarn
    - name: Setup Node.js
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version: "24"
        cache: 'yarn'
    - name: Install dependencies
      shell: bash
      run: yarn install --immutable
